<?php
/**
 * @desc JwtTokenTest.php 描述信息
 * @author imeepo(me@imeepo.com)
 * @date 2022/2/24 10:04
 */


namespace imeepo\Tests;


use imeepo\Jwt\JwtToken;

class JwtTokenTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function generateToken()
    {
        $user = [
            'id'  => 2022,
            'name'  => 'imeepo',
            'email' => 'imeepo@163.com'
        ];
        $token = JwtToken::generateToken($user);
        self::assertIsArray($token);
    }
}